theme: jekyll-theme-minimal
#description: "Machine-Learned Heuristic Of Ultimate Structural Energy"
#show_downloads: "false"
#logo: [Location of the logo]
#google_analytics: [Your Google Analytics tracking ID]
#title: [The title of your site]
